"""empty message

Revision ID: 0282203ebeff
Revises: 5f936ac4d0db
Create Date: 2024-03-11 00:08:34.855721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0282203ebeff'
down_revision = '5f936ac4d0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cellphone', sa.String(length=50), nullable=True))

    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.alter_column('origin',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('destination',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)

    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cellphone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.drop_column('cellphone')

    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.alter_column('destination',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('origin',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('clients_table', schema=None) as batch_op:
        batch_op.drop_column('cellphone')

    # ### end Alembic commands ###
