"""empty message

Revision ID: 5f936ac4d0db
Revises: c28df9925635
Create Date: 2024-03-10 23:17:28.559069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f936ac4d0db'
down_revision = 'c28df9925635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.Date(), nullable=True))

    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.String(length=100), nullable=True))
        batch_op.drop_column('destin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destin', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('destination')

    with op.batch_alter_table('clients_table', schema=None) as batch_op:
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###
