"""empty message

Revision ID: a4eb562a78d4
Revises: ecb025857a03
Create Date: 2024-03-11 21:24:37.795945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4eb562a78d4'
down_revision = 'ecb025857a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.alter_column('meals',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.alter_column('meals',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###
