"""empty message

Revision ID: c28df9925635
Revises: 
Create Date: 2024-03-10 22:44:21.084684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28df9925635'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients_table',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('users_table',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('packages_table',
    sa.Column('package_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('destin', sa.String(length=100), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_table.client_id'], ),
    sa.PrimaryKeyConstraint('package_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packages_table')
    op.drop_table('users_table')
    op.drop_table('clients_table')
    # ### end Alembic commands ###
