"""empty message

Revision ID: ecb025857a03
Revises: 66de897a8b03
Create Date: 2024-03-11 20:43:25.250647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecb025857a03'
down_revision = '66de897a8b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meals', sa.String(length=6), nullable=True))
        batch_op.drop_column('meal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal', mysql.ENUM('breakfast', 'lunch', 'dinner', 'all_inclusive'), nullable=True))
        batch_op.drop_column('meals')

    # ### end Alembic commands ###
