"""empty message

Revision ID: fa29e33fa3e8
Revises: 406dd7597eb3
Create Date: 2024-03-14 22:50:06.086488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa29e33fa3e8'
down_revision = '406dd7597eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.alter_column('travelers',
               existing_type=mysql.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages_table', schema=None) as batch_op:
        batch_op.alter_column('travelers',
               existing_type=sa.SmallInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
